name: Destroy AWS
run-name: Destroying from ${{ inputs.workspace }}

on:
  workflow_dispatch:
    inputs:
      ec2:
        description: "Destroy EC2"
        type: boolean
        default: false

      s3:
        description: "Destroy S3"
        type: boolean
        default: false

      rds:
        description: "Destroy RDS"
        type: boolean
        default: false

      workspace:
        description: "Workspace"
        required: true
        default: "aws1"
        type: choice
        options:
          - aws1
          - aws2

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: aws

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ########################################
      # AWS LOGIN
      ########################################
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      ########################################
      # Workspace Select / Create
      ########################################
      - name: Select Workspace
        run: terraform workspace select ${{ inputs.workspace }}

      ########################################
      # Build services list
      ########################################
      - name: Build services list
        id: build
        run: |
          SERVICES="["

          [ "${{ inputs.ec2 }}" == "true" ] && SERVICES="$SERVICES\"ec2\","
          [ "${{ inputs.s3 }}" == "true" ] && SERVICES="$SERVICES\"s3\","
          [ "${{ inputs.rds }}" == "true" ] && SERVICES="$SERVICES\"rds\","

          SERVICES="${SERVICES%,}]"

          if [ "$SERVICES" == "]" ]; then
            echo "Error: No services selected for destroy."
            exit 1
          fi

          echo "services=$SERVICES" >> $GITHUB_OUTPUT

      ########################################
      # Terraform Destroy
      ########################################
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="services_to_deploy=${{ steps.build.outputs.services }}"
