name: Destroy AWS
run-name: Destroying infrastructure

on:
  workflow_dispatch:
    inputs:
      destroy_mode:
        description: "Destroy Mode"
        required: true
        type: choice
        default: single
        options:
          - single
          - all

      workspace:
        description: "Workspace (used if destroy_mode = single)"
        required: false
        type: choice
        options:
         - datascience
         - devops
         - bigdata

      ec2:
        description: "Destroy EC2"
        type: boolean
        default: false
      s3:
        description: "Destroy S3"
        type: boolean
        default: false
      rds:
        description: "Destroy RDS"
        type: boolean
        default: false
      ecr:
        description: "Destroy ECR"
        type: boolean
        default: false
      ecs:
        description: "Destroy ECS"
        type: boolean
        default: false
      lambda:
        description: "Destroy Lambda"
        type: boolean
        default: false
      sns:
        description: "Destroy SNS"
        type: boolean
        default: false
      codecommit:
        description: "Destroy CodeCommit"
        type: boolean
        default: false
      codebuild:
        description: "Destroy CodeBuild"
        type: boolean
        default: false
      codepipeline:
        description: "Destroy CodePipeline"
        type: boolean
        default: false
      glue:
        description: "Destroy Glue"
        type: boolean
        default: false
      opensearch:
        description: "Destroy OpenSearch"
        type: boolean
        default: false
      sagemaker:
        description: "Destroy SageMaker"
        type: boolean
        default: false
      quicksight:
        description: "Destroy QuickSight"
        type: boolean
        default: false
      redshift:
        description: "Destroy redshift"
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: aws

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ########################################
      # AWS LOGIN (OIDC)
      ########################################
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::666127452756:role/terraform-deployer-role
          aws-region: eu-north-1

      ########################################
      # Setup Terraform
      ########################################
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -reconfigure

      ########################################
      # Build services list
      ########################################
      - name: Build services list
        id: build
        run: |
          SERVICES="["
          [ "${{ inputs.ec2 }}" == "true" ] && SERVICES="$SERVICES\"ec2\","
          [ "${{ inputs.s3 }}" == "true" ] && SERVICES="$SERVICES\"s3\","
          [ "${{ inputs.rds }}" == "true" ] && SERVICES="$SERVICES\"rds\","
          [ "${{ inputs.ecr }}" == "true" ] && SERVICES="$SERVICES\"ecr\","
          [ "${{ inputs.lambda }}" == "true" ] && SERVICES="$SERVICES\"lambda\","
          [ "${{ inputs.sns }}" == "true" ] && SERVICES="$SERVICES\"sns\","
          [ "${{ inputs.codecommit }}" == "true" ] && SERVICES="$SERVICES\"codecommit\","
          [ "${{ inputs.codebuild }}" == "true" ] && SERVICES="$SERVICES\"codebuild\","
          [ "${{ inputs.codepipeline }}" == "true" ] && SERVICES="$SERVICES\"codepipeline\","
          [ "${{ inputs.glue }}" == "true" ] && SERVICES="$SERVICES\"glue\","
          [ "${{ inputs.opensearch }}" == "true" ] && SERVICES="$SERVICES\"opensearch\","
          [ "${{ inputs.sagemaker }}" == "true" ] && SERVICES="$SERVICES\"sagemaker\","
          [ "${{ inputs.quicksight }}" == "true" ] && SERVICES="$SERVICES\"quicksight\","
          [ "${{ inputs.redshift }}" == "true" ] && SERVICES="$SERVICES\"redshift\","
          [ "${{ inputs.ecs }}" == "true" ] && SERVICES="$SERVICES\"ecs\","
          SERVICES="${SERVICES%,}]"

          if [ "$SERVICES" == "]" ]; then
            echo "Error: No services selected for destroy."
            exit 1
          fi

          echo "services=$SERVICES" >> $GITHUB_OUTPUT

      ########################################
      # Terraform Destroy
      ########################################
      - name: Terraform Destroy
        shell: bash
        run: |
          set -e

          if [ "${{ inputs.destroy_mode }}" = "all" ]; then
            echo "Destroying ALL workspaces..."

            for ws in $(terraform workspace list -no-color | sed 's/*//g'); do
              ws=$(echo "$ws" | xargs)

              if [ -n "$ws" ] && [ "$ws" != "default" ]; then
                echo "Switching to workspace: $ws"
                terraform workspace select "$ws"
                terraform destroy -auto-approve -var='services_to_deploy=${{ steps.build.outputs.services }}'
              fi
            done

          else
            echo "Destroying workspace: ${{ inputs.workspace }}"
            terraform workspace select "${{ inputs.workspace }}"
            terraform destroy -auto-approve -var='services_to_deploy=${{ steps.build.outputs.services }}'
          fi